apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "project.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "project.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "project.name" . }}
  replicas: {{ .Values.deployment.replicas }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "project.name" . }}
    spec:
      serviceAccountName: {{ .Values.serviceAccountName }}
      terminationGracePeriodSeconds: {{ .Values.deployment.terminationGracePeriodSeconds }}
      securityContext:
        runAsNonRoot: true
      containers:
      - name: postfix-exporter
        image: "{{ .Values.image.repository }}:{{ default .Chart.AppVersion .Values.image.tag }}"
        {{- with .Values.image.pullPolicy }}
        imagePullPolicy: {{ . }}
        {{- end }}
        ports:
        - containerPort: {{ .Values.deployment.metricsPort }}
          name: metrics
          protocol: TCP
        args:
          - --kubernetes.enable
          {{ if .Values.postfixServiceName }}
          - --kubernetes.service={{ .Values.postfixServiceName }}
          {{ end }}
          {{ if .Values.useTCPShowq }}
          - --postfix.showq_network=tcp
          {{ end }}
          {{- range .Values.deployment.extraArgs }}
          - {{ . }}
          {{- end }}
        {{- with .Values.deployment.resources }}
        resources: {{ toYaml . | nindent 12 }}
        {{- end }}
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          runAsUser: 65534
        livenessProbe:
          httpGet:
            path: /
            port: metrics
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /
            port: metrics
          initialDelaySeconds: 5
          periodSeconds: 10
      {{- if .Values.image.pullSecrets }}
      imagePullSecrets:
      {{- range .Values.image.pullSecrets }}
      - name: {{ . }}
      {{- end }}
      {{- end }}
      {{- with .Values.deployment.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.deployment.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.deployment.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
