name: Release Helm chart
on:
  push:
    branches:
      - master
    paths:
      - 'charts/postfix-exporter/Chart.yaml'
permissions:
  contents: write
  packages: write
  id-token: write
  attestations: write
jobs:
  release:
    uses: hsn723/actions/.github/workflows/helm-release.yml@41d028a3a7a0947c9fbd5ebd4b57d8f19e0bcc98 # v1.0.45
    secrets: inherit
    with:
      upload_as_oci: true
      chart_name: postfix-exporter
