name: Release Helm chart
on:
  push:
    branches:
      - master
    paths:
      - 'charts/postfix-exporter/Chart.yaml'
permissions:
  contents: write
  packages: write
  id-token: write
  attestations: write
jobs:
  release:
    uses: hsn723/actions/.github/workflows/helm-release.yml@5148379dc2d4c76ab7aa5bf0d8da84d0b333cb91 # v1.0.31
    secrets: inherit
    with:
      upload_as_oci: true
      chart_name: postfix-exporter
