name: Lint and test Helm charts
on:
  pull_request:
    paths:
      - 'charts/**'
      - '!**.md'
permissions:
  contents: read
jobs:
  lint-test:
    uses: hsn723/actions/.github/workflows/helm-lint.yml@3a9e9ad4bbf7fa37f2b1ac810d5d0c9cd06ebc63 # v1.0.48
    with:
      helm_extra_set_args: "--set=deployment.extraArgs={--no-postfix.logfile_must_exist}"
