name: Release Helm chart
on:
  push:
    branches:
      - master
    paths:
      - 'charts/postfix-exporter/Chart.yaml'
permissions:
  contents: write
  packages: write
  id-token: write
  attestations: write
jobs:
  release:
    uses: hsn723/actions/.github/workflows/helm-release.yml@c503c7b5fb7b07887fdc678505e69e37cff1b3f8 # v1.0.35
    secrets: inherit
    with:
      upload_as_oci: true
      chart_name: postfix-exporter
