name: Lint and test Helm charts
on:
  pull_request:
    paths:
      - 'charts/**'
      - '!**.md'
permissions:
  contents: read
jobs:
  lint-test:
    uses: hsn723/actions/.github/workflows/helm-lint.yml@47eeeef281da373b713e33dee8f0696a7c83e1c0 # v1.0.47
    with:
      helm_extra_set_args: "--set=deployment.extraArgs={--no-postfix.logfile_must_exist}"
