name: Lint and test Helm charts
on:
  pull_request:
    paths:
      - 'charts/**'
      - '!**.md'
permissions:
  contents: read
jobs:
  lint-test:
    uses: hsn723/actions/.github/workflows/helm-lint.yml@8513fd44855c269a7c10144d59cf6fae60fa4702 # v1.0.46
    with:
      helm_extra_set_args: "--set=deployment.extraArgs={--no-postfix.logfile_must_exist}"
