name: main
on:
  push:
    branches:
      - master
    tags-ignore:
      - '*'
  pull_request:
    branches:
      - master
permissions:
  contents: read
  pull-requests: write
jobs:
  verify:
    uses: hsn723/actions/.github/workflows/verify.yml@5148379dc2d4c76ab7aa5bf0d8da84d0b333cb91 # v1.0.31
    secrets: inherit
    with:
      lint-pre: |
        make libsystemd-dev
      additional-dry-run-setup: |
        make libsystemd-dev
        make gcc-aarch64-linux-gnu
