name: Tag and release
on:
  push:
    branches:
      - master
    paths:
      - VERSION
permissions:
  contents: write
  id-token: write
  packages: write
  attestations: write
jobs:
  release:
    uses: hsn723/actions/.github/workflows/release.yml@41d028a3a7a0947c9fbd5ebd4b57d8f19e0bcc98 # v1.0.45
    secrets: inherit
    with:
      additional-setup: |
        make libsystemd-dev
        make gcc-aarch64-linux-gnu
      upload-image-sbom: false
      disable-sudo: false
