name: Tag and release
on:
  push:
    branches:
      - master
    paths:
      - VERSION
permissions:
  contents: write
  id-token: write
  packages: write
  attestations: write
jobs:
  release:
    uses: hsn723/actions/.github/workflows/release.yml@5148379dc2d4c76ab7aa5bf0d8da84d0b333cb91 # v1.0.31
    secrets: inherit
    with:
      additional-setup: |
        make libsystemd-dev
        make gcc-aarch64-linux-gnu
      upload-image-sbom: false
